### ISSUE TITLE
Types do not implement `Copy` or other useful traits/methods, even if they could.

### ISSUE THREAD

**Issue by eddyb** [open-flash/rust-swf-fixed#1]
This also applies to other crates, too, but I just remembered I have to work around it in `flashback`.

In terms of derives, I generally suggest as many of these as possible:
```rust
#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
```

Also, there is no `epsilons` method to get the inner field, which means I have to use `transmute_copy` (I'd rather not do that but I wanted to make progress, at the time).

**Comment by demurgos** [comment]
Agreed that more traits would be useful: I had a similar situation recently were I need `Copy` or `Clone` on an enum from `swf-tree`. The list you proposed seems good.
Other interesting traits are numeric operations.

If you need some traits, feel free to send a PR.

**Comment by eddyb** [comment]
Ah oops, I also forgot `Default`.
