### ISSUE TITLE
There is no easy way to acces the epsilons/value.

### ISSUE THREAD

**Issue by eddyb** [open-flash/rust-swf-fixed#5]
Refiling so it doesn't get lost in https://github.com/open-flash/rust-swf-fixed/issues/1.

**Comment by demurgos** [comment]
Do you think the field should be public or use a getter? Given Rust semantics, I think that making the field public would be enough (there's no risk of mutating the value while it's used somewhere else).

**Comment by eddyb** [comment]
Making it public would be fine, yeah, and you can add accessors for `as_f32()` and `as_f64()`.
